### ISSUE TITLE
don't working

### ISSUE THREAD

**Issue by natandiasm** [jaumard/flare_splash_screen#1]
the animation does not start and does not change the screen

**Comment by natandiasm** [comment]
my code(main.dart): 

import 'package:flutter/material.dart';
import 'package:flare_splash_screen/flare_splash_screen.dart';

main() {
  runApp(MaterialApp(
    home: SplashScreen(
      'assets/cactus.flr',
      Home(),
      backgroundColor: Colors.white,
      alignment: Alignment.center,
      until: () => Future.delayed(Duration(seconds: 2)),
    ),
    title: "Splash Screen Test",
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Tseet"),
      ),
    );
  }
}

**Comment by jaumard** [comment]
Hey @natandiasm you didn't specify which animation to start :) check out example like this one https://github.com/jaumard/flare_splash_screen/blob/master/example/lib/main.dart#L19
