### ISSUE TITLE
isLoading.dart example is not working

### ISSUE THREAD

**Issue by tsinis** [jaumard/flare_splash_screen#11]
Hi, @jaumard

First of all thank you very much for the great plugin, but there is a problem with your example you provide. Specifically, it is **isLoading.dart** file. The example should point out possibility of initial splash screen being redirected to the home screen, as soon as some of the functions are complete (after 5sec. in your example), but after the initial splash animation stops — screen is not redirected to MyHomePage, even after _isLoading is correctly set to "false" value. Flutter doctor have no issues.

I have test it in real android device (you can see private video of it here): https://youtu.be/hm877rJre5A
and on iOS simulator (you can see private video of it here): https://youtu.be/JUS_LJel_Tg
Can you provide solution how to fix "isLoading" propery? Propety "until" is working fine, but i need to work with boolean values. Can you please take a look in your free time?

Thanks, dude.

P.S.
Also can you advice, how to show animation for few seconds, even if all functions are done with their job (so isLoading setted то false).

**Comment by jaumard** [comment]
Hello,

I'll check it out :) 
I'm using the `until` method so I might forget something about the boolean approach. 

 >Also can you advice, how to show animation for few seconds, even if all functions are done with their job (so isLoading setted то false).

Easier way I see is to timestamp your your functions before/after and if it's too fast for you just add `await Future.delayed(Duration(second: 3));` and it will add another 3 seconds to your animation :)

**Comment by tsinis** [comment]
> Hello,
> I'll check it out :)
> I'm using the until method so I might forget something about the boolean approach.
> 
> Also can you advice, how to show animation for few seconds, even if all functions are done with their job (so isLoading setted то false).
> 
> Easier way I see is to timestamp your your functions before/after and if it's too fast for you just add await Future.delayed(Duration(second: 3)); and it will add another 3 seconds to your animation :)

@jaumard
Yeah, seems there is workaround with "until" property, i made my this way:

```
  @override
  Widget build(BuildContext context) {
    return SplashScreen.navigate(
      name: 'intro.flr',
      next: MyHomePage(),
      startAnimation: '1',
      until: () async{
        await loadLongFunctionHere();
        await Future.delayed(Duration(seconds: 3));
      },
    );
  }
```
it wont neccesary be a async function (so there is no need actualy await), but it can be done both ways (sync or async). But it will be awesome, if you will bring isLoading function back! Anyway, awsome job dude.

**Comment by jaumard** [comment]
Should be ok with version 2.1.4 :)
Thanks for the report !
