### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by BND10706** [jaumard/flare_splash_screen#12]
I am new at this, and I tried to follow example, but it wont let me do my redirect to my Home().
I get this error.
The argument type Home cant be assigned to the parameter type 'Widget Function(BuildContext)'/

**Comment by jaumard** [comment]
Hello, 

Because you're supposed to pass a WidgetBuilder not a Widget so if you follow the examples (who are working ^^) you should put `(context) => Home()` and not just `Home()`
