### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by Condelab** [jaumard/flare_splash_screen#14]
Because flare_splash_screen 3.0.0 requires Flutter SDK version >=1.7.8 <2.0.0 and no versions of flare_splash_screen match >3.0.0 <4.0.0, flare_splash_screen ^3.0.0 is forbidden.
So, because my_app depends on flare_splash_screen ^3.0.0, version solving failed.

**Comment by jeremySrgt** [comment]
try updating all your dependencies in the pubspec.yaml and also update your flutter version to the last one

**Comment by tsinis** [comment]
Hey! I'm bumping it too, it does have nothing to do with flutter version. Developer of this package should updated dependency of flare_flutter to most recent version (since there is shadows and blur support, also as some optimizations). Thanks in advance!

**Comment by jaumard** [comment]
3.0.1 contains dep last version of rive now
