### ISSUE TITLE
Animation dont start

### ISSUE THREAD

**Issue by julioffigueiredo** [jaumard/flare_splash_screen#16]
I try with the anomation's example flare fire and it works, if I download a new one from flare site, the new animation dont work and dont redirect to the chosen screen.

**Comment by jaumard** [comment]
Did you change the animation's name too? Changing just the file is not enough

**Comment by julioffigueiredo** [comment]
Yes, I did. Added on yaml file and same name on widget. Sometimes animations dont start at all, other  cases it shows a image of animation and stop. But in all cases system never go to my home page.
Is there anything to do for download a animation on flare site?

**Comment by julioffigueiredo** [comment]
I uploaded a little example https://github.com/tuskinhu/splashscreen
If i run with your flr goes ok, if i run with other i downloaded it stucks on splash

![Screenshot_1579373943](https://user-images.githubusercontent.com/606731/72669028-b7beaf80-3a0b-11ea-86fb-b215e2a605fc.png)

**Comment by jaumard** [comment]
Sorry for the delay I totally forget about this, but from what I look on your exemple, you didn't change the animation name so of course another file will not start as it's most unlikely that the animation name is the same (in my example it's `startAnimation: '1',`) you need to change `1` by the animation name of the file you download in order the work :)
