### ISSUE TITLE
until not working

### ISSUE THREAD

**Issue by orgio** [jaumard/flare_splash_screen#18]
`SplashScreen.navigate(
          name: "assets/splash.flr",
          next:(_)=>MyHomePage(color,json) ,
          until: ()=>Future.delayed(Duration(seconds: 1)),
          fit: BoxFit.cover,
          startAnimation: "intro",
        )`

**Comment by orgio** [comment]
it takes 3 second which is my animation duration

**Comment by jaumard** [comment]
That is the correct behavior :) if your animation is more than until it wait until the end of animation, if not the animation is looping until "until" is done

**Comment by orgio** [comment]
thank you so much there is one more thing Navigator is not working inside MaterialApp do you know any solution?

**Comment by jaumard** [comment]
hum not sure I understand correctly do you have an example of the problem ?

**Comment by orgio** [comment]
![Capture](https://user-images.githubusercontent.com/27058809/76508876-0b88ca80-648a-11ea-9cf5-54ad7715ec69.PNG)

**Comment by jaumard** [comment]
Ho I see ! that's normal, if you want this to work you need to wrap SplashScreen with a `Builder` widget, then it should work.
Cheers

**Comment by orgio** [comment]
thank you so much nice guy
