### ISSUE TITLE
web navigation error

### ISSUE THREAD

**Issue by timeshift92** [jaumard/flare_splash_screen#19]
Hello, animation is works, but after navigate get error

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building TickerMode(mode: disabled):
setState() or markNeedsBuild() called during build.
This Overlay widget cannot be marked as needing to build because the framework is already in the
process of building widgets.  A widget can be marked as needing to be built during the build phase
only if one of its ancestors is currently building. This exception is allowed because the framework
builds parent widgets before children, which means a dirty descendant will always be built.
Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
Overlay-[LabeledGlobalKey<OverlayState>#a07a3]
The widget which was currently being built when the offending call was made was:
TickerMode

The relevant error-causing widget was:
MaterialApp org-dartlang-app:///packages/lynx_blog/main.dart:35:12
When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:flutter/src/widgets/framework.dart 3896:11                                    <fn>
package:flutter/src/widgets/framework.dart 3910:14                                    markNeedsBuild
package:flutter/src/widgets/framework.dart 1168:14                                    setState
package:flutter/src/widgets/overlay.dart 344:5                                        insertAll
package:flutter/src/widgets/routes.dart 44:24                                         install
package:flutter/src/widgets/routes.dart 181:11                                        install
package:flutter/src/widgets/routes.dart 959:11                                        install
package:flutter/src/widgets/navigator.dart 1883:13                                    pushReplacement
package:flare_splash_screen/flare_splash_screen.dart 135:27                           [_goToNext]
package:flare_splash_screen/flare_splash_screen.dart 118:11                           <fn>
package:flare_loading/flare_loading.dart 117:16                                       [_finished]
package:flare_loading/flare_loading.dart 153:7                                        advance
package:flare_flutter/flare_actor.dart 433:22                                         advance
package:flare_flutter/flare_actor.dart 339:5                                          [_instanceArtboard]
package:flare_flutter/flare_actor.dart 359:12                                         warmLoad
package:flare_flutter/flare_render_box.dart 257:10                                    load
package:flare_flutter/flare_render_box.dart 104:7                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/proxy_box.dart 883:11                                   attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/rendering/object.dart 2912:27                                     attach
package:flutter/src/foundation/node.dart 132:12                                       adoptChild
package:flutter/src/rendering/object.dart 1238:11                                     adoptChild
package:flutter/src/rendering/object.dart 3077:5                                      insert
package:flutter/src/widgets/overlay.dart 530:20                                       insertChildRenderObject
package:flutter/src/widgets/framework.dart 5295:35                                    attachRenderObject
package:flutter/src/widgets/framework.dart 3108:12                                    <fn>
package:flutter/src/widgets/framework.dart 4272:22                                    visitChildren
package:flutter/src/widgets/framework.dart 3107:5                                     attachRenderObject
package:flutter/src/widgets/framework.dart 3108:12                                    <fn>
package:flutter/src/widgets/framework.dart 4272:22                                    visitChildren
package:flutter/src/widgets/framework.dart 3107:5                                     attachRenderObject
package:flutter/src/widgets/framework.dart 3108:12                                    <fn>
package:flutter/src/widgets/framework.dart 4272:22                                    visitChildren
package:flutter/src/widgets/framework.dart 3107:5                                     attachRenderObject
package:flutter/src/widgets/framework.dart 3261:5                                     [_activateWithParent]
package:flutter/src/widgets/framework.dart 3183:17                                    inflateWidget
package:flutter/src/widgets/framework.dart 2988:12                                    updateChild
package:flutter/src/widgets/framework.dart 4243:16                                    performRebuild
package:flutter/src/widgets/framework.dart 3947:5                                     rebuild
package:flutter/src/widgets/framework.dart 4206:5                                     [_firstBuild]
package:flutter/src/widgets/framework.dart 4201:5                                     mount
package:flutter/src/widgets/framework.dart 3194:13                                    inflateWidget
package:flutter/src/widgets/framework.dart 2988:12                                    updateChild
package:flutter/src/widgets/framework.dart 5219:32                                    updateChildren
package:flutter/src/widgets/overlay.dart 606:17                                       update
package:flutter/src/widgets/framework.dart 2977:14                                    updateChild
package:flutter/src/widgets/framework.dart 4243:16                                    performRebuild
package:flutter/src/widgets/framework.dart 3947:5                                     rebuild
package:flutter/src/widgets/framework.dart 2432:31                                    buildScope
package:flutter/src/widgets/binding.dart 773:49                                       drawFrame
package:flutter/src/rendering/binding.dart 283:5                                      [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1102:15                                    [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1041:9                                     handleDrawFrame
package:flutter/src/scheduler/binding.dart 957:5                                      [_handleDrawFrame]
package:build_web_compilers/lib/_engine/engine.dart 181:21                            <fn>

════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: NoSuchMethodError: invalid member on null: 'status'

**Comment by jaumard** [comment]
It look like more like a problem on your side than an error on this package from the look of the logs as the crash come from your code not inside the package. Not sure how I can help with that

**Comment by timeshift92** [comment]
Thanks, i'ts my fail
