### ISSUE TITLE
The splash is delayed.

### ISSUE THREAD

**Issue by SuuSoJeat** [jaumard/flare_splash_screen#2]
Unlike the native splash screen that immediately started as soon as the user opened the app, this flare splash screen only started after the native splash screen finished. I was using this on Android.

Is this the default behavior or am I doing something wrong?

**Comment by jaumard** [comment]
You have no choice to have that native splash screen, as the Flutter view doesn't start right away you can't show a Flutter spashscreen directly. 
The trick I use is to put the native splash screen in one color (same as the flutter one) like this it give the illusion. Also be sure to do nothing in you main.dart before launching the splash screen or it will delay it (if you have to process or setup thing use `until` field and do it there)
