### ISSUE TITLE
still shows the white splash screen!

### ISSUE THREAD

**Issue by hewa-jalal** [jaumard/flare_splash_screen#22]
i am using the splash flare animation screen like this 

```
MaterialApp(
        home: SplashScreen.navigate(
          name: 'assets/splash.flr',
          next: (context) => WelcomePage(),
          until: () => Future.delayed(
            Duration(milliseconds: 4),
          ),
          startAnimation: '0',
          endAnimation: '4',
          loopAnimation: 'splash',
        ),
      )
```
but it still shows the initial white screen then the animation, how can this be fixed?

**Comment by jaumard** [comment]
If you don't want to the initial white screen you need to add a native splash screen by editing `LaunchScreen` on iOS and `launch_background.xml` on android. 

You can't have the flare splashscreen directly as flutter need time to initialized. On my app I generally put the first frame of the animation as native splashscreen to have smooth transition between the two splash screen
