### ISSUE TITLE
Rive support

### ISSUE THREAD

**Issue by muhammadidrees** [jaumard/flare_splash_screen#30]
With the breaking update of rive 1 to rive 2, the .flr file format is not supported anymore and all exports are made in a new format .riv. Neither there is any way to convert a .flr file to .riv nor there is any way to export a .flr file from the rive 2 app. This package needs to be updated to support the new format as the rive 1 app will soon be deprecated.

**Comment by jaumard** [comment]
Hello,

ho I didn't follow that in a while! I'll surely start to migrate those then thanks! Is there any documentation on how to do that ?

**Comment by muhammadidrees** [comment]
I haven't found any useful migration guide. Rive themselves have created a separate rive package leaving the flare package as is. :(

**Comment by JaffaKetchup** [comment]
Hello,
Is there any news on this, as new users (such as myself) are unable to create accounts for the old Flare app, meaning we can now only use .riv files. I have been relying on this working, so please can it be done as soon as possible.
Thanks,
Luka S

**Comment by jaumard** [comment]
My idea is to create a fork on my own repo and migrate it to rive, like this it will have a new name, but should keep the same API. I'll do that this week.

**Comment by jaumard** [comment]
I've started the migration guys, I'll keep you updated :)

**Comment by jaumard** [comment]
Here it is :) 
https://github.com/jaumard/rive_splash_screen 

I'm closing this issue, if you have feedbacks create issue on the new repo :) 
I love some
