### ISSUE TITLE
between "LaunchScreen" and "flare_splash_screen",A picture will appear.    build in release mode (IOS)

### ISSUE THREAD

**Issue by zhaoxwgit** [jaumard/flare_splash_screen#5]
i think this problem by the ios Life cycle。at the first restart or some time is ok。

**Comment by jaumard** [comment]
I don't understand the problem, do you have a sample to reproduce the problem please ?

**Comment by zhaoxwgit** [comment]
Except for the first boot of the installation and exit the application （click home button）for a period of time before opening it are all right.If it opens soon after exit，the problem will arise。

**Comment by zhaoxwgit** [comment]
Except for the first boot of the installation and exit the application （click home button）for a period of time are all right. but If it opens soon after exit，the problem will arise。

**Comment by zhaoxwgit** [comment]
> I don't understand the problem, do you have a sample to reproduce the problem please ?

between "LaunchScreen" and "flare_splash_screen",A picture will appear.   It should be the picture when app enter the background.

**Comment by zhaoxwgit** [comment]
> I don't understand the problem, do you have a sample to reproduce the problem please ?

between "LaunchScreen" and "flare_splash_screen",A picture will appear. It should be the picture when app enter the background.

**Comment by zhaoxwgit** [comment]
- (void)applicationDidEnterBackground:(UIApplication *)application
{
    self.window.hidden = YES;
}

- (void)applicationWillEnterForeground:(UIApplication *)application
{
    self.window.hidden = NO;
}

Interim solutions for my application

**Comment by zhaoxwgit** [comment]
tell me the solution ,if fixed
